apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort   # For Kind / local clusters
  selector:
    app: node
    version: green   # <-- THIS controls traffic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
